// GlyphBox Unicode Data
// Curated dataset of Unicode characters with names and keywords for search

const UNICODE_DATA = [
  // ── Emoji & Hearts ──────────────────────────────────────────────────
  { char: "❤", name: "Heavy Black Heart", keywords: ["heart", "love", "red", "romance"] },
  { char: "🧡", name: "Orange Heart", keywords: ["heart", "love", "orange"] },
  { char: "💛", name: "Yellow Heart", keywords: ["heart", "love", "yellow"] },
  { char: "💚", name: "Green Heart", keywords: ["heart", "love", "green"] },
  { char: "💙", name: "Blue Heart", keywords: ["heart", "love", "blue"] },
  { char: "💜", name: "Purple Heart", keywords: ["heart", "love", "purple"] },
  { char: "🖤", name: "Black Heart", keywords: ["heart", "love", "black"] },
  { char: "🤍", name: "White Heart", keywords: ["heart", "love", "white"] },
  { char: "🤎", name: "Brown Heart", keywords: ["heart", "love", "brown"] },
  { char: "💔", name: "Broken Heart", keywords: ["heart", "broken", "sad"] },
  { char: "❣", name: "Heavy Heart Exclamation Mark Ornament", keywords: ["heart", "exclamation"] },
  { char: "💕", name: "Two Hearts", keywords: ["heart", "love", "two"] },
  { char: "💞", name: "Revolving Hearts", keywords: ["heart", "love", "spin"] },
  { char: "💓", name: "Beating Heart", keywords: ["heart", "beating", "love"] },
  { char: "💗", name: "Growing Heart", keywords: ["heart", "growing", "love"] },
  { char: "💖", name: "Sparkling Heart", keywords: ["heart", "sparkling", "love"] },
  { char: "💘", name: "Heart with Arrow", keywords: ["heart", "arrow", "cupid"] },
  { char: "💝", name: "Heart with Ribbon", keywords: ["heart", "ribbon", "gift"] },
  { char: "♥", name: "Black Heart Suit", keywords: ["heart", "suit", "card"] },
  { char: "♡", name: "White Heart Suit", keywords: ["heart", "suit", "card", "white"] },

  // ── Stars & Sparkles ─────────────────────────────────────────────────
  { char: "★", name: "Black Star", keywords: ["star", "black", "solid"] },
  { char: "☆", name: "White Star", keywords: ["star", "white", "outline"] },
  { char: "✦", name: "Black Four Pointed Star", keywords: ["star", "four", "pointed"] },
  { char: "✧", name: "White Four Pointed Star", keywords: ["star", "four", "white"] },
  { char: "✨", name: "Sparkles", keywords: ["sparkle", "magic", "shine"] },
  { char: "✩", name: "Stress Outlined White Star", keywords: ["star", "outlined"] },
  { char: "✪", name: "Circled White Star", keywords: ["star", "circled"] },
  { char: "✫", name: "Open Centre Black Star", keywords: ["star", "open"] },
  { char: "✬", name: "Black Centre White Star", keywords: ["star", "black", "white"] },
  { char: "✭", name: "Outlined Black Star", keywords: ["star", "outlined", "black"] },
  { char: "✮", name: "Heavy Outlined Black Star", keywords: ["star", "heavy", "outlined"] },
  { char: "✯", name: "Pinwheel Star", keywords: ["star", "pinwheel"] },
  { char: "✰", name: "Shadowed White Star", keywords: ["star", "shadow", "white"] },
  { char: "⭐", name: "White Medium Star", keywords: ["star", "medium"] },
  { char: "🌟", name: "Glowing Star", keywords: ["star", "glowing", "shine"] },
  { char: "💫", name: "Dizzy", keywords: ["star", "dizzy", "spin"] },
  { char: "⚡", name: "High Voltage Sign", keywords: ["lightning", "bolt", "electric", "voltage"] },

  // ── Arrows ───────────────────────────────────────────────────────────
  { char: "→", name: "Rightwards Arrow", keywords: ["arrow", "right"] },
  { char: "←", name: "Leftwards Arrow", keywords: ["arrow", "left"] },
  { char: "↑", name: "Upwards Arrow", keywords: ["arrow", "up"] },
  { char: "↓", name: "Downwards Arrow", keywords: ["arrow", "down"] },
  { char: "↔", name: "Left Right Arrow", keywords: ["arrow", "left", "right", "both"] },
  { char: "↕", name: "Up Down Arrow", keywords: ["arrow", "up", "down"] },
  { char: "↖", name: "North West Arrow", keywords: ["arrow", "northwest", "diagonal"] },
  { char: "↗", name: "North East Arrow", keywords: ["arrow", "northeast", "diagonal"] },
  { char: "↘", name: "South East Arrow", keywords: ["arrow", "southeast", "diagonal"] },
  { char: "↙", name: "South West Arrow", keywords: ["arrow", "southwest", "diagonal"] },
  { char: "⇒", name: "Rightwards Double Arrow", keywords: ["arrow", "double", "right", "implies"] },
  { char: "⇐", name: "Leftwards Double Arrow", keywords: ["arrow", "double", "left"] },
  { char: "⇔", name: "Left Right Double Arrow", keywords: ["arrow", "double", "both", "iff"] },
  { char: "⇑", name: "Upwards Double Arrow", keywords: ["arrow", "double", "up"] },
  { char: "⇓", name: "Downwards Double Arrow", keywords: ["arrow", "double", "down"] },
  { char: "➡", name: "Black Rightwards Arrow", keywords: ["arrow", "right", "black", "bold"] },
  { char: "⬅", name: "Black Leftwards Arrow", keywords: ["arrow", "left", "black", "bold"] },
  { char: "⬆", name: "Black Upwards Arrow", keywords: ["arrow", "up", "black", "bold"] },
  { char: "⬇", name: "Black Downwards Arrow", keywords: ["arrow", "down", "black", "bold"] },
  { char: "↩", name: "Leftwards Arrow with Hook", keywords: ["arrow", "return", "hook"] },
  { char: "↪", name: "Rightwards Arrow with Hook", keywords: ["arrow", "hook", "right"] },
  { char: "↻", name: "Clockwise Open Circle Arrow", keywords: ["arrow", "clockwise", "rotate"] },
  { char: "↺", name: "Anticlockwise Open Circle Arrow", keywords: ["arrow", "counterclockwise", "rotate"] },
  { char: "⟵", name: "Long Leftwards Arrow", keywords: ["arrow", "long", "left"] },
  { char: "⟶", name: "Long Rightwards Arrow", keywords: ["arrow", "long", "right"] },
  { char: "⟷", name: "Long Left Right Arrow", keywords: ["arrow", "long", "both"] },
  { char: "⟹", name: "Long Rightwards Double Arrow", keywords: ["arrow", "long", "double", "implies"] },
  { char: "⟺", name: "Long Left Right Double Arrow", keywords: ["arrow", "long", "double", "iff"] },
  { char: "↦", name: "Rightwards Arrow from Bar", keywords: ["arrow", "maps", "to"] },
  { char: "↣", name: "Rightwards Tail Arrow", keywords: ["arrow", "tail", "injection"] },
  { char: "↠", name: "Rightwards Two Headed Arrow", keywords: ["arrow", "two", "head", "surjection"] },

  // ── Mathematical Symbols ─────────────────────────────────────────────
  { char: "∀", name: "For All", keywords: ["math", "forall", "universal", "quantifier"] },
  { char: "∃", name: "There Exists", keywords: ["math", "exists", "existential", "quantifier"] },
  { char: "∄", name: "There Does Not Exist", keywords: ["math", "not", "exists"] },
  { char: "∂", name: "Partial Differential", keywords: ["math", "partial", "differential", "calculus"] },
  { char: "∇", name: "Nabla", keywords: ["math", "nabla", "gradient", "del"] },
  { char: "∈", name: "Element Of", keywords: ["math", "element", "in", "set"] },
  { char: "∉", name: "Not an Element Of", keywords: ["math", "not", "element", "set"] },
  { char: "∋", name: "Contains as Member", keywords: ["math", "contains", "set"] },
  { char: "∅", name: "Empty Set", keywords: ["math", "empty", "set", "null"] },
  { char: "∩", name: "Intersection", keywords: ["math", "intersection", "set", "cap"] },
  { char: "∪", name: "Union", keywords: ["math", "union", "set", "cup"] },
  { char: "⊂", name: "Subset Of", keywords: ["math", "subset", "set"] },
  { char: "⊃", name: "Superset Of", keywords: ["math", "superset", "set"] },
  { char: "⊆", name: "Subset Of or Equal To", keywords: ["math", "subset", "equal", "set"] },
  { char: "⊇", name: "Superset Of or Equal To", keywords: ["math", "superset", "equal", "set"] },
  { char: "⊕", name: "Circled Plus", keywords: ["math", "xor", "direct", "sum", "oplus"] },
  { char: "⊗", name: "Circled Times", keywords: ["math", "tensor", "product", "otimes"] },
  { char: "⊥", name: "Up Tack", keywords: ["math", "perpendicular", "bottom", "false"] },
  { char: "⊤", name: "Down Tack", keywords: ["math", "top", "true"] },
  { char: "⋅", name: "Dot Operator", keywords: ["math", "dot", "multiply", "product"] },
  { char: "×", name: "Multiplication Sign", keywords: ["math", "multiply", "times", "cross"] },
  { char: "÷", name: "Division Sign", keywords: ["math", "divide", "division"] },
  { char: "±", name: "Plus-Minus Sign", keywords: ["math", "plus", "minus", "plusminus"] },
  { char: "∓", name: "Minus-or-Plus Sign", keywords: ["math", "minus", "plus"] },
  { char: "√", name: "Square Root", keywords: ["math", "sqrt", "root", "radical"] },
  { char: "∛", name: "Cube Root", keywords: ["math", "cube", "root"] },
  { char: "∜", name: "Fourth Root", keywords: ["math", "fourth", "root"] },
  { char: "∞", name: "Infinity", keywords: ["math", "infinity", "infinite"] },
  { char: "∝", name: "Proportional To", keywords: ["math", "proportional"] },
  { char: "∼", name: "Tilde Operator", keywords: ["math", "tilde", "similar"] },
  { char: "≈", name: "Almost Equal To", keywords: ["math", "approximately", "approx"] },
  { char: "≅", name: "Approximately Equal To", keywords: ["math", "congruent", "approximately"] },
  { char: "≠", name: "Not Equal To", keywords: ["math", "not", "equal", "neq"] },
  { char: "≡", name: "Identical To", keywords: ["math", "identical", "equiv"] },
  { char: "≤", name: "Less-Than or Equal To", keywords: ["math", "less", "equal", "leq"] },
  { char: "≥", name: "Greater-Than or Equal To", keywords: ["math", "greater", "equal", "geq"] },
  { char: "≪", name: "Much Less-Than", keywords: ["math", "much", "less"] },
  { char: "≫", name: "Much Greater-Than", keywords: ["math", "much", "greater"] },
  { char: "⟨", name: "Mathematical Left Angle Bracket", keywords: ["math", "angle", "bracket", "left", "bra"] },
  { char: "⟩", name: "Mathematical Right Angle Bracket", keywords: ["math", "angle", "bracket", "right", "ket"] },
  { char: "∑", name: "N-Ary Summation", keywords: ["math", "sum", "sigma"] },
  { char: "∏", name: "N-Ary Product", keywords: ["math", "product", "pi"] },
  { char: "∐", name: "N-Ary Coproduct", keywords: ["math", "coproduct"] },
  { char: "∫", name: "Integral", keywords: ["math", "integral", "calculus"] },
  { char: "∬", name: "Double Integral", keywords: ["math", "double", "integral"] },
  { char: "∭", name: "Triple Integral", keywords: ["math", "triple", "integral"] },
  { char: "∮", name: "Contour Integral", keywords: ["math", "contour", "integral"] },
  { char: "∧", name: "Logical And", keywords: ["math", "and", "wedge", "logic"] },
  { char: "∨", name: "Logical Or", keywords: ["math", "or", "vee", "logic"] },
  { char: "¬", name: "Not Sign", keywords: ["math", "not", "logic", "negation"] },
  { char: "∴", name: "Therefore", keywords: ["math", "therefore", "logic"] },
  { char: "∵", name: "Because", keywords: ["math", "because", "logic"] },
  { char: "⌊", name: "Left Floor", keywords: ["math", "floor", "bracket"] },
  { char: "⌋", name: "Right Floor", keywords: ["math", "floor", "bracket"] },
  { char: "⌈", name: "Left Ceiling", keywords: ["math", "ceiling", "bracket"] },
  { char: "⌉", name: "Right Ceiling", keywords: ["math", "ceiling", "bracket"] },
  { char: "⊂̃", name: "Subset With Not Equal", keywords: ["math", "subset", "proper"] },
  { char: "℃", name: "Degree Celsius", keywords: ["degree", "celsius", "temperature"] },
  { char: "℉", name: "Degree Fahrenheit", keywords: ["degree", "fahrenheit", "temperature"] },
  { char: "°", name: "Degree Sign", keywords: ["degree", "angle", "temperature"] },
  { char: "′", name: "Prime", keywords: ["prime", "foot", "minute"] },
  { char: "″", name: "Double Prime", keywords: ["prime", "double", "inch", "second"] },
  { char: "‴", name: "Triple Prime", keywords: ["prime", "triple"] },
  { char: "⁰", name: "Superscript Zero", keywords: ["superscript", "zero", "exponent"] },
  { char: "¹", name: "Superscript One", keywords: ["superscript", "one", "exponent"] },
  { char: "²", name: "Superscript Two", keywords: ["superscript", "two", "squared"] },
  { char: "³", name: "Superscript Three", keywords: ["superscript", "three", "cubed"] },
  { char: "⁴", name: "Superscript Four", keywords: ["superscript", "four"] },
  { char: "⁵", name: "Superscript Five", keywords: ["superscript", "five"] },
  { char: "⁶", name: "Superscript Six", keywords: ["superscript", "six"] },
  { char: "⁷", name: "Superscript Seven", keywords: ["superscript", "seven"] },
  { char: "⁸", name: "Superscript Eight", keywords: ["superscript", "eight"] },
  { char: "⁹", name: "Superscript Nine", keywords: ["superscript", "nine"] },
  { char: "ⁿ", name: "Superscript Latin Small Letter N", keywords: ["superscript", "n", "exponent"] },
  { char: "₀", name: "Subscript Zero", keywords: ["subscript", "zero"] },
  { char: "₁", name: "Subscript One", keywords: ["subscript", "one"] },
  { char: "₂", name: "Subscript Two", keywords: ["subscript", "two"] },
  { char: "₃", name: "Subscript Three", keywords: ["subscript", "three"] },
  { char: "₄", name: "Subscript Four", keywords: ["subscript", "four"] },
  { char: "₅", name: "Subscript Five", keywords: ["subscript", "five"] },
  { char: "₆", name: "Subscript Six", keywords: ["subscript", "six"] },
  { char: "₇", name: "Subscript Seven", keywords: ["subscript", "seven"] },
  { char: "₈", name: "Subscript Eight", keywords: ["subscript", "eight"] },
  { char: "₉", name: "Subscript Nine", keywords: ["subscript", "nine"] },
  { char: "α", name: "Greek Small Letter Alpha", keywords: ["greek", "alpha", "letter"] },
  { char: "β", name: "Greek Small Letter Beta", keywords: ["greek", "beta", "letter"] },
  { char: "γ", name: "Greek Small Letter Gamma", keywords: ["greek", "gamma", "letter"] },
  { char: "δ", name: "Greek Small Letter Delta", keywords: ["greek", "delta", "letter"] },
  { char: "ε", name: "Greek Small Letter Epsilon", keywords: ["greek", "epsilon", "letter"] },
  { char: "ζ", name: "Greek Small Letter Zeta", keywords: ["greek", "zeta", "letter"] },
  { char: "η", name: "Greek Small Letter Eta", keywords: ["greek", "eta", "letter"] },
  { char: "θ", name: "Greek Small Letter Theta", keywords: ["greek", "theta", "letter", "angle"] },
  { char: "ι", name: "Greek Small Letter Iota", keywords: ["greek", "iota", "letter"] },
  { char: "κ", name: "Greek Small Letter Kappa", keywords: ["greek", "kappa", "letter"] },
  { char: "λ", name: "Greek Small Letter Lambda", keywords: ["greek", "lambda", "letter", "function"] },
  { char: "μ", name: "Greek Small Letter Mu", keywords: ["greek", "mu", "micro", "letter"] },
  { char: "ν", name: "Greek Small Letter Nu", keywords: ["greek", "nu", "letter"] },
  { char: "ξ", name: "Greek Small Letter Xi", keywords: ["greek", "xi", "letter"] },
  { char: "π", name: "Greek Small Letter Pi", keywords: ["greek", "pi", "math", "ratio"] },
  { char: "ρ", name: "Greek Small Letter Rho", keywords: ["greek", "rho", "letter"] },
  { char: "σ", name: "Greek Small Letter Sigma", keywords: ["greek", "sigma", "letter", "sum"] },
  { char: "τ", name: "Greek Small Letter Tau", keywords: ["greek", "tau", "letter"] },
  { char: "υ", name: "Greek Small Letter Upsilon", keywords: ["greek", "upsilon", "letter"] },
  { char: "φ", name: "Greek Small Letter Phi", keywords: ["greek", "phi", "letter", "angle"] },
  { char: "χ", name: "Greek Small Letter Chi", keywords: ["greek", "chi", "letter"] },
  { char: "ψ", name: "Greek Small Letter Psi", keywords: ["greek", "psi", "letter"] },
  { char: "ω", name: "Greek Small Letter Omega", keywords: ["greek", "omega", "letter"] },
  { char: "Α", name: "Greek Capital Letter Alpha", keywords: ["greek", "alpha", "capital"] },
  { char: "Β", name: "Greek Capital Letter Beta", keywords: ["greek", "beta", "capital"] },
  { char: "Γ", name: "Greek Capital Letter Gamma", keywords: ["greek", "gamma", "capital"] },
  { char: "Δ", name: "Greek Capital Letter Delta", keywords: ["greek", "delta", "capital", "change"] },
  { char: "Ε", name: "Greek Capital Letter Epsilon", keywords: ["greek", "epsilon", "capital"] },
  { char: "Ζ", name: "Greek Capital Letter Zeta", keywords: ["greek", "zeta", "capital"] },
  { char: "Η", name: "Greek Capital Letter Eta", keywords: ["greek", "eta", "capital"] },
  { char: "Θ", name: "Greek Capital Letter Theta", keywords: ["greek", "theta", "capital"] },
  { char: "Ι", name: "Greek Capital Letter Iota", keywords: ["greek", "iota", "capital"] },
  { char: "Κ", name: "Greek Capital Letter Kappa", keywords: ["greek", "kappa", "capital"] },
  { char: "Λ", name: "Greek Capital Letter Lambda", keywords: ["greek", "lambda", "capital"] },
  { char: "Μ", name: "Greek Capital Letter Mu", keywords: ["greek", "mu", "capital"] },
  { char: "Ν", name: "Greek Capital Letter Nu", keywords: ["greek", "nu", "capital"] },
  { char: "Ξ", name: "Greek Capital Letter Xi", keywords: ["greek", "xi", "capital"] },
  { char: "Π", name: "Greek Capital Letter Pi", keywords: ["greek", "pi", "capital"] },
  { char: "Ρ", name: "Greek Capital Letter Rho", keywords: ["greek", "rho", "capital"] },
  { char: "Σ", name: "Greek Capital Letter Sigma", keywords: ["greek", "sigma", "capital"] },
  { char: "Τ", name: "Greek Capital Letter Tau", keywords: ["greek", "tau", "capital"] },
  { char: "Υ", name: "Greek Capital Letter Upsilon", keywords: ["greek", "upsilon", "capital"] },
  { char: "Φ", name: "Greek Capital Letter Phi", keywords: ["greek", "phi", "capital"] },
  { char: "Χ", name: "Greek Capital Letter Chi", keywords: ["greek", "chi", "capital"] },
  { char: "Ψ", name: "Greek Capital Letter Psi", keywords: ["greek", "psi", "capital"] },
  { char: "Ω", name: "Greek Capital Letter Omega", keywords: ["greek", "omega", "capital"] },

  // ── Currency ─────────────────────────────────────────────────────────
  { char: "€", name: "Euro Sign", keywords: ["currency", "euro", "money"] },
  { char: "£", name: "Pound Sign", keywords: ["currency", "pound", "sterling", "money"] },
  { char: "¥", name: "Yen Sign", keywords: ["currency", "yen", "yuan", "money", "japan", "china"] },
  { char: "¢", name: "Cent Sign", keywords: ["currency", "cent", "money"] },
  { char: "₹", name: "Indian Rupee Sign", keywords: ["currency", "rupee", "india", "money"] },
  { char: "₽", name: "Ruble Sign", keywords: ["currency", "ruble", "russia", "money"] },
  { char: "₩", name: "Won Sign", keywords: ["currency", "won", "korea", "money"] },
  { char: "₪", name: "New Sheqel Sign", keywords: ["currency", "shekel", "israel", "money"] },
  { char: "₺", name: "Turkish Lira Sign", keywords: ["currency", "lira", "turkey", "money"] },
  { char: "₿", name: "Bitcoin Sign", keywords: ["currency", "bitcoin", "crypto", "money"] },
  { char: "₮", name: "Tugrik Sign", keywords: ["currency", "tugrik", "mongolia", "money"] },
  { char: "₦", name: "Naira Sign", keywords: ["currency", "naira", "nigeria", "money"] },
  { char: "$", name: "Dollar Sign", keywords: ["currency", "dollar", "money", "usd"] },
  { char: "₡", name: "Colon Sign", keywords: ["currency", "colon", "costa rica"] },
  { char: "₴", name: "Hryvnia Sign", keywords: ["currency", "hryvnia", "ukraine"] },

  // ── Punctuation & Typography ──────────────────────────────────────────
  { char: "…", name: "Horizontal Ellipsis", keywords: ["ellipsis", "dots", "continuation"] },
  { char: "—", name: "Em Dash", keywords: ["dash", "em", "hyphen"] },
  { char: "–", name: "En Dash", keywords: ["dash", "en", "hyphen"] },
  { char: "‐", name: "Hyphen", keywords: ["hyphen", "dash"] },
  { char: "‑", name: "Non-Breaking Hyphen", keywords: ["hyphen", "non-breaking"] },
  { char: "\u201C", name: "Left Double Quotation Mark", keywords: ["quote", "left", "double", "curly"] },
  { char: "\u201D", name: "Right Double Quotation Mark", keywords: ["quote", "right", "double", "curly"] },
  { char: "\u2018", name: "Left Single Quotation Mark", keywords: ["quote", "left", "single", "curly"] },
  { char: "\u2019", name: "Right Single Quotation Mark", keywords: ["quote", "right", "single", "curly"] },
  { char: "«", name: "Left-Pointing Double Angle Quotation Mark", keywords: ["quote", "guillemet", "left"] },
  { char: "»", name: "Right-Pointing Double Angle Quotation Mark", keywords: ["quote", "guillemet", "right"] },
  { char: "‹", name: "Single Left-Pointing Angle Quotation Mark", keywords: ["quote", "guillemet", "single", "left"] },
  { char: "›", name: "Single Right-Pointing Angle Quotation Mark", keywords: ["quote", "guillemet", "single", "right"] },
  { char: "•", name: "Bullet", keywords: ["bullet", "dot", "list"] },
  { char: "◦", name: "White Bullet", keywords: ["bullet", "white", "list"] },
  { char: "‣", name: "Triangular Bullet", keywords: ["bullet", "triangular"] },
  { char: "⁃", name: "Hyphen Bullet", keywords: ["bullet", "hyphen"] },
  { char: "‒", name: "Figure Dash", keywords: ["dash", "figure"] },
  { char: "⁠", name: "Word Joiner", keywords: ["space", "joiner", "invisible"] },
  { char: "‍", name: "Zero Width Joiner", keywords: ["zwj", "joiner", "invisible"] },
  { char: "‌", name: "Zero Width Non-Joiner", keywords: ["zwnj", "joiner", "invisible"] },
  { char: "§", name: "Section Sign", keywords: ["section", "paragraph", "legal"] },
  { char: "¶", name: "Pilcrow Sign", keywords: ["pilcrow", "paragraph", "mark"] },
  { char: "†", name: "Dagger", keywords: ["dagger", "cross", "footnote"] },
  { char: "‡", name: "Double Dagger", keywords: ["dagger", "double", "footnote"] },
  { char: "™", name: "Trade Mark Sign", keywords: ["trademark", "tm", "brand"] },
  { char: "®", name: "Registered Sign", keywords: ["registered", "trademark", "brand"] },
  { char: "©", name: "Copyright Sign", keywords: ["copyright", "brand"] },
  { char: "℗", name: "Sound Recording Copyright", keywords: ["copyright", "phonogram", "sound"] },
  { char: "№", name: "Numero Sign", keywords: ["numero", "number", "no"] },
  { char: "℅", name: "Care Of", keywords: ["care", "of", "address"] },
  { char: "‰", name: "Per Mille Sign", keywords: ["per", "mille", "thousand"] },
  { char: "‱", name: "Per Ten Thousand Sign", keywords: ["per", "ten", "thousand"] },
  { char: "℃", name: "Degree Celsius", keywords: ["celsius", "temperature", "degree"] },
  { char: "℉", name: "Degree Fahrenheit", keywords: ["fahrenheit", "temperature", "degree"] },

  // ── Geometric Shapes ─────────────────────────────────────────────────
  { char: "■", name: "Black Square", keywords: ["square", "black", "shape"] },
  { char: "□", name: "White Square", keywords: ["square", "white", "shape"] },
  { char: "▪", name: "Black Small Square", keywords: ["square", "small", "black"] },
  { char: "▫", name: "White Small Square", keywords: ["square", "small", "white"] },
  { char: "▲", name: "Black Up-Pointing Triangle", keywords: ["triangle", "up", "black"] },
  { char: "▼", name: "Black Down-Pointing Triangle", keywords: ["triangle", "down", "black"] },
  { char: "▶", name: "Black Right-Pointing Triangle", keywords: ["triangle", "right", "play"] },
  { char: "◀", name: "Black Left-Pointing Triangle", keywords: ["triangle", "left"] },
  { char: "△", name: "White Up-Pointing Triangle", keywords: ["triangle", "up", "white"] },
  { char: "▽", name: "White Down-Pointing Triangle", keywords: ["triangle", "down", "white"] },
  { char: "◆", name: "Black Diamond", keywords: ["diamond", "black"] },
  { char: "◇", name: "White Diamond", keywords: ["diamond", "white"] },
  { char: "○", name: "White Circle", keywords: ["circle", "white"] },
  { char: "●", name: "Black Circle", keywords: ["circle", "black"] },
  { char: "◎", name: "Bullseye", keywords: ["circle", "bullseye", "target"] },
  { char: "◉", name: "Fisheye", keywords: ["circle", "fisheye"] },
  { char: "◯", name: "Large Circle", keywords: ["circle", "large"] },
  { char: "⬤", name: "Black Large Circle", keywords: ["circle", "large", "black"] },
  { char: "⬜", name: "White Large Square", keywords: ["square", "large", "white"] },
  { char: "⬛", name: "Black Large Square", keywords: ["square", "large", "black"] },
  { char: "🔴", name: "Red Circle", keywords: ["circle", "red"] },
  { char: "🟠", name: "Orange Circle", keywords: ["circle", "orange"] },
  { char: "🟡", name: "Yellow Circle", keywords: ["circle", "yellow"] },
  { char: "🟢", name: "Green Circle", keywords: ["circle", "green"] },
  { char: "🔵", name: "Blue Circle", keywords: ["circle", "blue"] },
  { char: "🟣", name: "Purple Circle", keywords: ["circle", "purple"] },
  { char: "⚫", name: "Black Circle", keywords: ["circle", "black"] },
  { char: "⚪", name: "White Circle", keywords: ["circle", "white"] },

  // ── Miscellaneous Symbols ─────────────────────────────────────────────
  { char: "☀", name: "Black Sun with Rays", keywords: ["sun", "sunny", "weather"] },
  { char: "🌙", name: "Crescent Moon", keywords: ["moon", "crescent", "night"] },
  { char: "🌕", name: "Full Moon", keywords: ["moon", "full"] },
  { char: "⭕", name: "Heavy Large Circle", keywords: ["circle", "large", "heavy"] },
  { char: "❌", name: "Cross Mark", keywords: ["cross", "wrong", "no", "x"] },
  { char: "✅", name: "White Heavy Check Mark", keywords: ["check", "yes", "correct"] },
  { char: "☑", name: "Ballot Box with Check", keywords: ["checkbox", "check", "tick"] },
  { char: "☒", name: "Ballot Box with X", keywords: ["checkbox", "x", "wrong"] },
  { char: "✓", name: "Check Mark", keywords: ["check", "tick", "yes"] },
  { char: "✔", name: "Heavy Check Mark", keywords: ["check", "tick", "heavy"] },
  { char: "✗", name: "Ballot X", keywords: ["x", "wrong", "cross"] },
  { char: "✘", name: "Heavy Ballot X", keywords: ["x", "wrong", "heavy"] },
  { char: "☐", name: "Ballot Box", keywords: ["checkbox", "box"] },
  { char: "⚠", name: "Warning Sign", keywords: ["warning", "alert", "caution"] },
  { char: "⛔", name: "No Entry", keywords: ["no", "entry", "stop", "forbidden"] },
  { char: "🚫", name: "Prohibited", keywords: ["no", "prohibited", "forbidden"] },
  { char: "❓", name: "Black Question Mark Ornament", keywords: ["question", "mark"] },
  { char: "❔", name: "White Question Mark Ornament", keywords: ["question", "white"] },
  { char: "❗", name: "Heavy Exclamation Mark Ornament", keywords: ["exclamation", "important"] },
  { char: "❕", name: "White Exclamation Mark Ornament", keywords: ["exclamation", "white"] },
  { char: "ℹ", name: "Information Source", keywords: ["info", "information"] },
  { char: "✉", name: "Envelope", keywords: ["envelope", "mail", "email"] },
  { char: "☎", name: "Black Telephone", keywords: ["phone", "telephone"] },
  { char: "⌚", name: "Watch", keywords: ["watch", "time", "clock"] },
  { char: "⏰", name: "Alarm Clock", keywords: ["alarm", "clock", "time"] },
  { char: "⌛", name: "Hourglass", keywords: ["hourglass", "time", "wait"] },
  { char: "⏳", name: "Hourglass with Flowing Sand", keywords: ["hourglass", "sand", "time"] },
  { char: "🔑", name: "Key", keywords: ["key", "lock", "access"] },
  { char: "🔒", name: "Locked", keywords: ["lock", "locked", "secure"] },
  { char: "🔓", name: "Unlocked", keywords: ["lock", "unlocked"] },
  { char: "💡", name: "Electric Light Bulb", keywords: ["bulb", "light", "idea"] },
  { char: "🔥", name: "Fire", keywords: ["fire", "flame", "hot"] },
  { char: "💎", name: "Gem Stone", keywords: ["gem", "diamond", "jewel"] },
  { char: "🎵", name: "Musical Note", keywords: ["music", "note", "sound"] },
  { char: "🎶", name: "Multiple Musical Notes", keywords: ["music", "notes", "sound"] },
  { char: "♩", name: "Quarter Note", keywords: ["music", "note", "quarter"] },
  { char: "♪", name: "Eighth Note", keywords: ["music", "note", "eighth"] },
  { char: "♫", name: "Beamed Eighth Notes", keywords: ["music", "notes", "beamed"] },
  { char: "♬", name: "Beamed Sixteenth Notes", keywords: ["music", "notes", "sixteenth"] },
  { char: "♭", name: "Music Flat Sign", keywords: ["music", "flat"] },
  { char: "♯", name: "Music Sharp Sign", keywords: ["music", "sharp", "hash"] },
  { char: "♮", name: "Music Natural Sign", keywords: ["music", "natural"] },

  // ── Dingbats ─────────────────────────────────────────────────────────
  { char: "✂", name: "Black Scissors", keywords: ["scissors", "cut"] },
  { char: "✎", name: "Lower Right Pencil", keywords: ["pencil", "write", "edit"] },
  { char: "✏", name: "Pencil", keywords: ["pencil", "write", "edit"] },
  { char: "✐", name: "Upper Right Pencil", keywords: ["pencil", "write"] },
  { char: "✑", name: "White Nib", keywords: ["nib", "pen", "write"] },
  { char: "✒", name: "Black Nib", keywords: ["nib", "pen", "write", "black"] },
  { char: "✍", name: "Writing Hand", keywords: ["writing", "hand", "sign"] },
  { char: "✋", name: "Raised Hand", keywords: ["hand", "raised", "stop"] },
  { char: "👋", name: "Waving Hand Sign", keywords: ["hand", "wave", "hello"] },
  { char: "👍", name: "Thumbs Up Sign", keywords: ["thumbs", "up", "like", "good"] },
  { char: "👎", name: "Thumbs Down Sign", keywords: ["thumbs", "down", "dislike", "bad"] },
  { char: "☝", name: "White Up Pointing Index", keywords: ["finger", "point", "up", "index"] },
  { char: "👆", name: "Backhand Index Pointing Up", keywords: ["finger", "point", "up"] },
  { char: "👇", name: "Backhand Index Pointing Down", keywords: ["finger", "point", "down"] },
  { char: "👈", name: "Backhand Index Pointing Left", keywords: ["finger", "point", "left"] },
  { char: "👉", name: "Backhand Index Pointing Right", keywords: ["finger", "point", "right"] },
  { char: "🌐", name: "Globe with Meridians", keywords: ["globe", "world", "internet"] },
  { char: "📌", name: "Round Pushpin", keywords: ["pin", "pushpin", "location"] },
  { char: "📍", name: "Round Pushpin", keywords: ["pin", "location", "map"] },
  { char: "🏠", name: "House Building", keywords: ["house", "home", "building"] },
  { char: "🏆", name: "Trophy", keywords: ["trophy", "award", "winner"] },
  { char: "🎯", name: "Direct Hit", keywords: ["target", "bullseye", "aim"] },
  { char: "🎲", name: "Game Die", keywords: ["dice", "game", "random"] },
  { char: "🎮", name: "Video Game", keywords: ["game", "controller", "play"] },
  { char: "🚀", name: "Rocket", keywords: ["rocket", "space", "launch"] },
  { char: "🛸", name: "Flying Saucer", keywords: ["ufo", "flying", "saucer", "alien"] },
  { char: "🌈", name: "Rainbow", keywords: ["rainbow", "color", "pride"] },
  { char: "☁", name: "Cloud", keywords: ["cloud", "weather"] },
  { char: "⛅", name: "Sun Behind Cloud", keywords: ["cloud", "sun", "weather", "partly"] },
  { char: "❄", name: "Snowflake", keywords: ["snow", "snowflake", "cold", "winter"] },
  { char: "🔮", name: "Crystal Ball", keywords: ["crystal", "ball", "magic", "fortune"] },
  { char: "🧲", name: "Magnet", keywords: ["magnet", "magnetic", "attract"] },
  { char: "⚙", name: "Gear", keywords: ["gear", "settings", "cog"] },
  { char: "🔧", name: "Wrench", keywords: ["wrench", "tool", "repair"] },
  { char: "🔨", name: "Hammer", keywords: ["hammer", "tool", "build"] },
  { char: "⚒", name: "Hammer and Pick", keywords: ["hammer", "pick", "tools"] },
  { char: "🔬", name: "Microscope", keywords: ["microscope", "science", "lab"] },
  { char: "🔭", name: "Telescope", keywords: ["telescope", "astronomy", "star"] },

  // ── Mathematical Alphanumeric Symbols (Double-Struck) ────────────────
  { char: "𝔸", name: "Mathematical Double-Struck Capital A", keywords: ["double", "struck", "A", "math", "blackboard"] },
  { char: "𝔹", name: "Mathematical Double-Struck Capital B", keywords: ["double", "struck", "B", "math", "blackboard"] },
  { char: "ℂ", name: "Double-Struck Capital C", keywords: ["double", "struck", "C", "complex", "math"] },
  { char: "𝔻", name: "Mathematical Double-Struck Capital D", keywords: ["double", "struck", "D", "math"] },
  { char: "𝔼", name: "Mathematical Double-Struck Capital E", keywords: ["double", "struck", "E", "math"] },
  { char: "𝔽", name: "Mathematical Double-Struck Capital F", keywords: ["double", "struck", "F", "math"] },
  { char: "𝔾", name: "Mathematical Double-Struck Capital G", keywords: ["double", "struck", "G", "math"] },
  { char: "ℍ", name: "Double-Struck Capital H", keywords: ["double", "struck", "H", "quaternion", "math"] },
  { char: "𝕀", name: "Mathematical Double-Struck Capital I", keywords: ["double", "struck", "I", "math"] },
  { char: "𝕁", name: "Mathematical Double-Struck Capital J", keywords: ["double", "struck", "J", "math"] },
  { char: "𝕂", name: "Mathematical Double-Struck Capital K", keywords: ["double", "struck", "K", "math"] },
  { char: "𝕃", name: "Mathematical Double-Struck Capital L", keywords: ["double", "struck", "L", "math"] },
  { char: "𝕄", name: "Mathematical Double-Struck Capital M", keywords: ["double", "struck", "M", "math"] },
  { char: "ℕ", name: "Double-Struck Capital N", keywords: ["double", "struck", "N", "natural", "math"] },
  { char: "𝕆", name: "Mathematical Double-Struck Capital O", keywords: ["double", "struck", "O", "math"] },
  { char: "ℙ", name: "Double-Struck Capital P", keywords: ["double", "struck", "P", "prime", "math"] },
  { char: "ℚ", name: "Double-Struck Capital Q", keywords: ["double", "struck", "Q", "rational", "math"] },
  { char: "ℝ", name: "Double-Struck Capital R", keywords: ["double", "struck", "R", "real", "math"] },
  { char: "𝕊", name: "Mathematical Double-Struck Capital S", keywords: ["double", "struck", "S", "math"] },
  { char: "𝕋", name: "Mathematical Double-Struck Capital T", keywords: ["double", "struck", "T", "math"] },
  { char: "𝕌", name: "Mathematical Double-Struck Capital U", keywords: ["double", "struck", "U", "math"] },
  { char: "𝕍", name: "Mathematical Double-Struck Capital V", keywords: ["double", "struck", "V", "math"] },
  { char: "𝕎", name: "Mathematical Double-Struck Capital W", keywords: ["double", "struck", "W", "math"] },
  { char: "𝕏", name: "Mathematical Double-Struck Capital X", keywords: ["double", "struck", "X", "math", "twitter"] },
  { char: "𝕐", name: "Mathematical Double-Struck Capital Y", keywords: ["double", "struck", "Y", "math"] },
  { char: "ℤ", name: "Double-Struck Capital Z", keywords: ["double", "struck", "Z", "integer", "math"] },
  { char: "𝕒", name: "Mathematical Double-Struck Small a", keywords: ["double", "struck", "a", "math"] },
  { char: "𝕓", name: "Mathematical Double-Struck Small b", keywords: ["double", "struck", "b", "math"] },
  { char: "𝕔", name: "Mathematical Double-Struck Small c", keywords: ["double", "struck", "c", "math"] },
  { char: "𝕕", name: "Mathematical Double-Struck Small d", keywords: ["double", "struck", "d", "math"] },
  { char: "𝕖", name: "Mathematical Double-Struck Small e", keywords: ["double", "struck", "e", "math"] },
  { char: "𝕗", name: "Mathematical Double-Struck Small f", keywords: ["double", "struck", "f", "math"] },
  { char: "𝕘", name: "Mathematical Double-Struck Small g", keywords: ["double", "struck", "g", "math"] },
  { char: "𝕙", name: "Mathematical Double-Struck Small h", keywords: ["double", "struck", "h", "math"] },
  { char: "𝕚", name: "Mathematical Double-Struck Small i", keywords: ["double", "struck", "i", "math"] },
  { char: "𝕛", name: "Mathematical Double-Struck Small j", keywords: ["double", "struck", "j", "math"] },
  { char: "𝕜", name: "Mathematical Double-Struck Small k", keywords: ["double", "struck", "k", "math"] },
  { char: "𝕝", name: "Mathematical Double-Struck Small l", keywords: ["double", "struck", "l", "math"] },
  { char: "𝕞", name: "Mathematical Double-Struck Small m", keywords: ["double", "struck", "m", "math"] },
  { char: "𝕟", name: "Mathematical Double-Struck Small n", keywords: ["double", "struck", "n", "math"] },
  { char: "𝕠", name: "Mathematical Double-Struck Small o", keywords: ["double", "struck", "o", "math"] },
  { char: "𝕡", name: "Mathematical Double-Struck Small p", keywords: ["double", "struck", "p", "math"] },
  { char: "𝕢", name: "Mathematical Double-Struck Small q", keywords: ["double", "struck", "q", "math"] },
  { char: "𝕣", name: "Mathematical Double-Struck Small r", keywords: ["double", "struck", "r", "math"] },
  { char: "𝕤", name: "Mathematical Double-Struck Small s", keywords: ["double", "struck", "s", "math"] },
  { char: "𝕥", name: "Mathematical Double-Struck Small t", keywords: ["double", "struck", "t", "math"] },
  { char: "𝕦", name: "Mathematical Double-Struck Small u", keywords: ["double", "struck", "u", "math"] },
  { char: "𝕧", name: "Mathematical Double-Struck Small v", keywords: ["double", "struck", "v", "math"] },
  { char: "𝕨", name: "Mathematical Double-Struck Small w", keywords: ["double", "struck", "w", "math"] },
  { char: "𝕩", name: "Mathematical Double-Struck Small x", keywords: ["double", "struck", "x", "math"] },
  { char: "𝕪", name: "Mathematical Double-Struck Small y", keywords: ["double", "struck", "y", "math"] },
  { char: "𝕫", name: "Mathematical Double-Struck Small z", keywords: ["double", "struck", "z", "math"] },

  // ── Mathematical Monospace ────────────────────────────────────────────
  { char: "𝙰", name: "Mathematical Monospace Capital A", keywords: ["monospace", "A", "math", "typewriter"] },
  { char: "𝙱", name: "Mathematical Monospace Capital B", keywords: ["monospace", "B", "math", "typewriter"] },
  { char: "𝙲", name: "Mathematical Monospace Capital C", keywords: ["monospace", "C", "math", "typewriter"] },
  { char: "𝙳", name: "Mathematical Monospace Capital D", keywords: ["monospace", "D", "math", "typewriter"] },
  { char: "𝙴", name: "Mathematical Monospace Capital E", keywords: ["monospace", "E", "math", "typewriter"] },
  { char: "𝙵", name: "Mathematical Monospace Capital F", keywords: ["monospace", "F", "math", "typewriter"] },
  { char: "𝙶", name: "Mathematical Monospace Capital G", keywords: ["monospace", "G", "math", "typewriter"] },
  { char: "𝙷", name: "Mathematical Monospace Capital H", keywords: ["monospace", "H", "math", "typewriter"] },
  { char: "𝙸", name: "Mathematical Monospace Capital I", keywords: ["monospace", "I", "math", "typewriter"] },
  { char: "𝙹", name: "Mathematical Monospace Capital J", keywords: ["monospace", "J", "math", "typewriter"] },
  { char: "𝙺", name: "Mathematical Monospace Capital K", keywords: ["monospace", "K", "math", "typewriter"] },
  { char: "𝙻", name: "Mathematical Monospace Capital L", keywords: ["monospace", "L", "math", "typewriter"] },
  { char: "𝙼", name: "Mathematical Monospace Capital M", keywords: ["monospace", "M", "math", "typewriter"] },
  { char: "𝙽", name: "Mathematical Monospace Capital N", keywords: ["monospace", "N", "math", "typewriter"] },
  { char: "𝙾", name: "Mathematical Monospace Capital O", keywords: ["monospace", "O", "math", "typewriter"] },
  { char: "𝙿", name: "Mathematical Monospace Capital P", keywords: ["monospace", "P", "math", "typewriter"] },
  { char: "𝚀", name: "Mathematical Monospace Capital Q", keywords: ["monospace", "Q", "math", "typewriter"] },
  { char: "𝚁", name: "Mathematical Monospace Capital R", keywords: ["monospace", "R", "math", "typewriter"] },
  { char: "𝚂", name: "Mathematical Monospace Capital S", keywords: ["monospace", "S", "math", "typewriter"] },
  { char: "𝚃", name: "Mathematical Monospace Capital T", keywords: ["monospace", "T", "math", "typewriter"] },
  { char: "𝚄", name: "Mathematical Monospace Capital U", keywords: ["monospace", "U", "math", "typewriter"] },
  { char: "𝚅", name: "Mathematical Monospace Capital V", keywords: ["monospace", "V", "math", "typewriter"] },
  { char: "𝚆", name: "Mathematical Monospace Capital W", keywords: ["monospace", "W", "math", "typewriter"] },
  { char: "𝚇", name: "Mathematical Monospace Capital X", keywords: ["monospace", "X", "math", "typewriter"] },
  { char: "𝚈", name: "Mathematical Monospace Capital Y", keywords: ["monospace", "Y", "math", "typewriter"] },
  { char: "𝚉", name: "Mathematical Monospace Capital Z", keywords: ["monospace", "Z", "math", "typewriter"] },

  // ── Fraktur / Blackletter ─────────────────────────────────────────────
  { char: "𝔄", name: "Mathematical Fraktur Capital A", keywords: ["fraktur", "A", "gothic", "blackletter"] },
  { char: "𝔅", name: "Mathematical Fraktur Capital B", keywords: ["fraktur", "B", "gothic", "blackletter"] },
  { char: "ℭ", name: "Fraktur Capital C", keywords: ["fraktur", "C", "gothic", "blackletter"] },
  { char: "𝔇", name: "Mathematical Fraktur Capital D", keywords: ["fraktur", "D", "gothic", "blackletter"] },
  { char: "𝔈", name: "Mathematical Fraktur Capital E", keywords: ["fraktur", "E", "gothic", "blackletter"] },
  { char: "𝔉", name: "Mathematical Fraktur Capital F", keywords: ["fraktur", "F", "gothic", "blackletter"] },
  { char: "𝔊", name: "Mathematical Fraktur Capital G", keywords: ["fraktur", "G", "gothic", "blackletter"] },
  { char: "ℌ", name: "Fraktur Capital H", keywords: ["fraktur", "H", "gothic", "blackletter"] },
  { char: "ℑ", name: "Black-Letter Capital I", keywords: ["fraktur", "I", "imaginary", "blackletter"] },
  { char: "𝔍", name: "Mathematical Fraktur Capital J", keywords: ["fraktur", "J", "gothic", "blackletter"] },
  { char: "𝔎", name: "Mathematical Fraktur Capital K", keywords: ["fraktur", "K", "gothic", "blackletter"] },
  { char: "𝔏", name: "Mathematical Fraktur Capital L", keywords: ["fraktur", "L", "gothic", "blackletter"] },
  { char: "𝔐", name: "Mathematical Fraktur Capital M", keywords: ["fraktur", "M", "gothic", "blackletter"] },
  { char: "𝔑", name: "Mathematical Fraktur Capital N", keywords: ["fraktur", "N", "gothic", "blackletter"] },
  { char: "𝔒", name: "Mathematical Fraktur Capital O", keywords: ["fraktur", "O", "gothic", "blackletter"] },
  { char: "𝔓", name: "Mathematical Fraktur Capital P", keywords: ["fraktur", "P", "gothic", "blackletter"] },
  { char: "𝔔", name: "Mathematical Fraktur Capital Q", keywords: ["fraktur", "Q", "gothic", "blackletter"] },
  { char: "ℜ", name: "Black-Letter Capital R", keywords: ["fraktur", "R", "real", "blackletter"] },
  { char: "𝔖", name: "Mathematical Fraktur Capital S", keywords: ["fraktur", "S", "gothic", "blackletter"] },
  { char: "𝔗", name: "Mathematical Fraktur Capital T", keywords: ["fraktur", "T", "gothic", "blackletter"] },
  { char: "𝔘", name: "Mathematical Fraktur Capital U", keywords: ["fraktur", "U", "gothic", "blackletter"] },
  { char: "𝔙", name: "Mathematical Fraktur Capital V", keywords: ["fraktur", "V", "gothic", "blackletter"] },
  { char: "𝔚", name: "Mathematical Fraktur Capital W", keywords: ["fraktur", "W", "gothic", "blackletter"] },
  { char: "𝔛", name: "Mathematical Fraktur Capital X", keywords: ["fraktur", "X", "gothic", "blackletter"] },
  { char: "𝔜", name: "Mathematical Fraktur Capital Y", keywords: ["fraktur", "Y", "gothic", "blackletter"] },
  { char: "ℨ", name: "Black-Letter Capital Z", keywords: ["fraktur", "Z", "blackletter"] },

  // ── Script / Calligraphic ─────────────────────────────────────────────
  { char: "𝒜", name: "Mathematical Script Capital A", keywords: ["script", "A", "calligraphy", "cursive"] },
  { char: "ℬ", name: "Script Capital B", keywords: ["script", "B", "calligraphy", "cursive"] },
  { char: "𝒞", name: "Mathematical Script Capital C", keywords: ["script", "C", "calligraphy", "cursive"] },
  { char: "𝒟", name: "Mathematical Script Capital D", keywords: ["script", "D", "calligraphy", "cursive"] },
  { char: "ℰ", name: "Script Capital E", keywords: ["script", "E", "calligraphy", "cursive"] },
  { char: "ℱ", name: "Script Capital F", keywords: ["script", "F", "calligraphy", "cursive"] },
  { char: "𝒢", name: "Mathematical Script Capital G", keywords: ["script", "G", "calligraphy", "cursive"] },
  { char: "ℋ", name: "Script Capital H", keywords: ["script", "H", "calligraphy", "cursive"] },
  { char: "ℐ", name: "Script Capital I", keywords: ["script", "I", "calligraphy", "cursive"] },
  { char: "𝒥", name: "Mathematical Script Capital J", keywords: ["script", "J", "calligraphy", "cursive"] },
  { char: "𝒦", name: "Mathematical Script Capital K", keywords: ["script", "K", "calligraphy", "cursive"] },
  { char: "ℒ", name: "Script Capital L", keywords: ["script", "L", "calligraphy", "cursive"] },
  { char: "ℳ", name: "Script Capital M", keywords: ["script", "M", "calligraphy", "cursive"] },
  { char: "𝒩", name: "Mathematical Script Capital N", keywords: ["script", "N", "calligraphy", "cursive"] },
  { char: "𝒪", name: "Mathematical Script Capital O", keywords: ["script", "O", "calligraphy", "cursive"] },
  { char: "𝒫", name: "Mathematical Script Capital P", keywords: ["script", "P", "calligraphy", "cursive"] },
  { char: "𝒬", name: "Mathematical Script Capital Q", keywords: ["script", "Q", "calligraphy", "cursive"] },
  { char: "ℛ", name: "Script Capital R", keywords: ["script", "R", "calligraphy", "cursive"] },
  { char: "𝒮", name: "Mathematical Script Capital S", keywords: ["script", "S", "calligraphy", "cursive"] },
  { char: "𝒯", name: "Mathematical Script Capital T", keywords: ["script", "T", "calligraphy", "cursive"] },
  { char: "𝒰", name: "Mathematical Script Capital U", keywords: ["script", "U", "calligraphy", "cursive"] },
  { char: "𝒱", name: "Mathematical Script Capital V", keywords: ["script", "V", "calligraphy", "cursive"] },
  { char: "𝒲", name: "Mathematical Script Capital W", keywords: ["script", "W", "calligraphy", "cursive"] },
  { char: "𝒳", name: "Mathematical Script Capital X", keywords: ["script", "X", "calligraphy", "cursive"] },
  { char: "𝒴", name: "Mathematical Script Capital Y", keywords: ["script", "Y", "calligraphy", "cursive"] },
  { char: "𝒵", name: "Mathematical Script Capital Z", keywords: ["script", "Z", "calligraphy", "cursive"] },
  { char: "𝒶", name: "Mathematical Script Small a", keywords: ["script", "a", "calligraphy", "cursive"] },
  { char: "𝒷", name: "Mathematical Script Small b", keywords: ["script", "b", "calligraphy", "cursive"] },
  { char: "𝒸", name: "Mathematical Script Small c", keywords: ["script", "c", "calligraphy", "cursive"] },
  { char: "𝒹", name: "Mathematical Script Small d", keywords: ["script", "d", "calligraphy", "cursive"] },
  { char: "ℯ", name: "Script Small e", keywords: ["script", "e", "calligraphy", "cursive"] },
  { char: "𝒻", name: "Mathematical Script Small f", keywords: ["script", "f", "calligraphy", "cursive"] },
  { char: "ℊ", name: "Script Small g", keywords: ["script", "g", "calligraphy", "cursive"] },
  { char: "𝒽", name: "Mathematical Script Small h", keywords: ["script", "h", "calligraphy", "cursive"] },
  { char: "𝒾", name: "Mathematical Script Small i", keywords: ["script", "i", "calligraphy", "cursive"] },
  { char: "𝒿", name: "Mathematical Script Small j", keywords: ["script", "j", "calligraphy", "cursive"] },
  { char: "𝓀", name: "Mathematical Script Small k", keywords: ["script", "k", "calligraphy", "cursive"] },
  { char: "𝓁", name: "Mathematical Script Small l", keywords: ["script", "l", "calligraphy", "cursive"] },
  { char: "𝓂", name: "Mathematical Script Small m", keywords: ["script", "m", "calligraphy", "cursive"] },
  { char: "𝓃", name: "Mathematical Script Small n", keywords: ["script", "n", "calligraphy", "cursive"] },
  { char: "ℴ", name: "Script Small o", keywords: ["script", "o", "calligraphy", "cursive"] },
  { char: "𝓅", name: "Mathematical Script Small p", keywords: ["script", "p", "calligraphy", "cursive"] },
  { char: "𝓆", name: "Mathematical Script Small q", keywords: ["script", "q", "calligraphy", "cursive"] },
  { char: "𝓇", name: "Mathematical Script Small r", keywords: ["script", "r", "calligraphy", "cursive"] },
  { char: "𝓈", name: "Mathematical Script Small s", keywords: ["script", "s", "calligraphy", "cursive"] },
  { char: "𝓉", name: "Mathematical Script Small t", keywords: ["script", "t", "calligraphy", "cursive"] },
  { char: "𝓊", name: "Mathematical Script Small u", keywords: ["script", "u", "calligraphy", "cursive"] },
  { char: "𝓋", name: "Mathematical Script Small v", keywords: ["script", "v", "calligraphy", "cursive"] },
  { char: "𝓌", name: "Mathematical Script Small w", keywords: ["script", "w", "calligraphy", "cursive"] },
  { char: "𝓍", name: "Mathematical Script Small x", keywords: ["script", "x", "calligraphy", "cursive"] },
  { char: "𝓎", name: "Mathematical Script Small y", keywords: ["script", "y", "calligraphy", "cursive"] },
  { char: "𝓏", name: "Mathematical Script Small z", keywords: ["script", "z", "calligraphy", "cursive"] },

  // ── Circled Numbers & Letters ─────────────────────────────────────────
  { char: "①", name: "Circled Digit One", keywords: ["circle", "number", "1", "one"] },
  { char: "②", name: "Circled Digit Two", keywords: ["circle", "number", "2", "two"] },
  { char: "③", name: "Circled Digit Three", keywords: ["circle", "number", "3", "three"] },
  { char: "④", name: "Circled Digit Four", keywords: ["circle", "number", "4", "four"] },
  { char: "⑤", name: "Circled Digit Five", keywords: ["circle", "number", "5", "five"] },
  { char: "⑥", name: "Circled Digit Six", keywords: ["circle", "number", "6", "six"] },
  { char: "⑦", name: "Circled Digit Seven", keywords: ["circle", "number", "7", "seven"] },
  { char: "⑧", name: "Circled Digit Eight", keywords: ["circle", "number", "8", "eight"] },
  { char: "⑨", name: "Circled Digit Nine", keywords: ["circle", "number", "9", "nine"] },
  { char: "⑩", name: "Circled Digit Ten", keywords: ["circle", "number", "10", "ten"] },
  { char: "⓪", name: "Circled Digit Zero", keywords: ["circle", "number", "0", "zero"] },
  { char: "Ⓐ", name: "Circled Latin Capital Letter A", keywords: ["circle", "letter", "A"] },
  { char: "Ⓑ", name: "Circled Latin Capital Letter B", keywords: ["circle", "letter", "B"] },
  { char: "Ⓒ", name: "Circled Latin Capital Letter C", keywords: ["circle", "letter", "C"] },
  { char: "Ⓓ", name: "Circled Latin Capital Letter D", keywords: ["circle", "letter", "D"] },
  { char: "Ⓔ", name: "Circled Latin Capital Letter E", keywords: ["circle", "letter", "E"] },
  { char: "Ⓕ", name: "Circled Latin Capital Letter F", keywords: ["circle", "letter", "F"] },
  { char: "Ⓖ", name: "Circled Latin Capital Letter G", keywords: ["circle", "letter", "G"] },
  { char: "Ⓗ", name: "Circled Latin Capital Letter H", keywords: ["circle", "letter", "H"] },
  { char: "Ⓘ", name: "Circled Latin Capital Letter I", keywords: ["circle", "letter", "I"] },
  { char: "Ⓙ", name: "Circled Latin Capital Letter J", keywords: ["circle", "letter", "J"] },
  { char: "Ⓚ", name: "Circled Latin Capital Letter K", keywords: ["circle", "letter", "K"] },
  { char: "Ⓛ", name: "Circled Latin Capital Letter L", keywords: ["circle", "letter", "L"] },
  { char: "Ⓜ", name: "Circled Latin Capital Letter M", keywords: ["circle", "letter", "M"] },
  { char: "Ⓝ", name: "Circled Latin Capital Letter N", keywords: ["circle", "letter", "N"] },
  { char: "Ⓞ", name: "Circled Latin Capital Letter O", keywords: ["circle", "letter", "O"] },
  { char: "Ⓟ", name: "Circled Latin Capital Letter P", keywords: ["circle", "letter", "P"] },
  { char: "Ⓠ", name: "Circled Latin Capital Letter Q", keywords: ["circle", "letter", "Q"] },
  { char: "Ⓡ", name: "Circled Latin Capital Letter R", keywords: ["circle", "letter", "R"] },
  { char: "Ⓢ", name: "Circled Latin Capital Letter S", keywords: ["circle", "letter", "S"] },
  { char: "Ⓣ", name: "Circled Latin Capital Letter T", keywords: ["circle", "letter", "T"] },
  { char: "Ⓤ", name: "Circled Latin Capital Letter U", keywords: ["circle", "letter", "U"] },
  { char: "Ⓥ", name: "Circled Latin Capital Letter V", keywords: ["circle", "letter", "V"] },
  { char: "Ⓦ", name: "Circled Latin Capital Letter W", keywords: ["circle", "letter", "W"] },
  { char: "Ⓧ", name: "Circled Latin Capital Letter X", keywords: ["circle", "letter", "X"] },
  { char: "Ⓨ", name: "Circled Latin Capital Letter Y", keywords: ["circle", "letter", "Y"] },
  { char: "Ⓩ", name: "Circled Latin Capital Letter Z", keywords: ["circle", "letter", "Z"] },

  // ── Emoji Faces & People ──────────────────────────────────────────────
  { char: "😀", name: "Grinning Face", keywords: ["smile", "happy", "grin", "face"] },
  { char: "😃", name: "Grinning Face with Big Eyes", keywords: ["smile", "happy", "face", "eyes"] },
  { char: "😄", name: "Grinning Face with Smiling Eyes", keywords: ["smile", "happy", "face"] },
  { char: "😁", name: "Beaming Face with Smiling Eyes", keywords: ["smile", "happy", "beam", "face"] },
  { char: "😆", name: "Grinning Squinting Face", keywords: ["laugh", "happy", "squint", "face"] },
  { char: "😅", name: "Grinning Face with Sweat", keywords: ["sweat", "smile", "nervous", "face"] },
  { char: "🤣", name: "Rolling on the Floor Laughing", keywords: ["laugh", "lol", "rofl", "funny"] },
  { char: "😂", name: "Face with Tears of Joy", keywords: ["laugh", "cry", "joy", "lol", "funny"] },
  { char: "🙂", name: "Slightly Smiling Face", keywords: ["smile", "slight", "face"] },
  { char: "😊", name: "Smiling Face with Smiling Eyes", keywords: ["smile", "happy", "blush"] },
  { char: "😇", name: "Smiling Face with Halo", keywords: ["angel", "halo", "innocent", "face"] },
  { char: "🥰", name: "Smiling Face with Hearts", keywords: ["love", "hearts", "adore", "face"] },
  { char: "😍", name: "Smiling Face with Heart-Eyes", keywords: ["love", "heart", "eyes", "face"] },
  { char: "🤩", name: "Star-Struck", keywords: ["star", "eyes", "excited", "wow"] },
  { char: "😘", name: "Face Blowing a Kiss", keywords: ["kiss", "love", "face"] },
  { char: "😗", name: "Kissing Face", keywords: ["kiss", "face"] },
  { char: "😙", name: "Kissing Face with Smiling Eyes", keywords: ["kiss", "smile", "face"] },
  { char: "😚", name: "Kissing Face with Closed Eyes", keywords: ["kiss", "closed", "face"] },
  { char: "😋", name: "Face Savoring Food", keywords: ["food", "yum", "delicious", "face"] },
  { char: "😛", name: "Face with Tongue", keywords: ["tongue", "face", "playful"] },
  { char: "😜", name: "Winking Face with Tongue", keywords: ["wink", "tongue", "playful"] },
  { char: "😝", name: "Squinting Face with Tongue", keywords: ["tongue", "squint", "face"] },
  { char: "🤪", name: "Zany Face", keywords: ["crazy", "zany", "wild", "face"] },
  { char: "🤨", name: "Face with Raised Eyebrow", keywords: ["eyebrow", "suspicious", "face"] },
  { char: "🧐", name: "Face with Monocle", keywords: ["monocle", "fancy", "investigate", "face"] },
  { char: "🤓", name: "Nerd Face", keywords: ["nerd", "geek", "glasses", "face"] },
  { char: "😎", name: "Smiling Face with Sunglasses", keywords: ["cool", "sunglasses", "face"] },
  { char: "🥸", name: "Disguised Face", keywords: ["disguise", "glasses", "nose", "face"] },
  { char: "🤩", name: "Star-Struck", keywords: ["star", "eyes", "amazing", "face"] },
  { char: "🥳", name: "Partying Face", keywords: ["party", "celebrate", "birthday", "face"] },
  { char: "😏", name: "Smirking Face", keywords: ["smirk", "smug", "face"] },
  { char: "😒", name: "Unamused Face", keywords: ["unamused", "bored", "face"] },
  { char: "😞", name: "Disappointed Face", keywords: ["disappointed", "sad", "face"] },
  { char: "😔", name: "Pensive Face", keywords: ["pensive", "sad", "face"] },
  { char: "😟", name: "Worried Face", keywords: ["worried", "concerned", "face"] },
  { char: "😕", name: "Confused Face", keywords: ["confused", "face"] },
  { char: "🙁", name: "Slightly Frowning Face", keywords: ["frown", "sad", "face"] },
  { char: "☹", name: "Frowning Face", keywords: ["frown", "sad", "face"] },
  { char: "😣", name: "Persevering Face", keywords: ["persevere", "struggle", "face"] },
  { char: "😖", name: "Confounded Face", keywords: ["confounded", "confused", "face"] },
  { char: "😫", name: "Tired Face", keywords: ["tired", "exhausted", "face"] },
  { char: "🥱", name: "Yawning Face", keywords: ["yawn", "tired", "sleepy", "face"] },
  { char: "😩", name: "Weary Face", keywords: ["weary", "tired", "face"] },
  { char: "🥺", name: "Pleading Face", keywords: ["pleading", "puppy", "cute", "face"] },
  { char: "😢", name: "Crying Face", keywords: ["cry", "sad", "tear", "face"] },
  { char: "😭", name: "Loudly Crying Face", keywords: ["cry", "sob", "sad", "face"] },
  { char: "😤", name: "Face with Steam from Nose", keywords: ["angry", "steam", "triumph", "face"] },
  { char: "😠", name: "Angry Face", keywords: ["angry", "mad", "face"] },
  { char: "😡", name: "Pouting Face", keywords: ["pout", "angry", "red", "face"] },
  { char: "🤬", name: "Face with Symbols on Mouth", keywords: ["swear", "angry", "curse", "face"] },
  { char: "😈", name: "Smiling Face with Horns", keywords: ["devil", "evil", "horns", "face"] },
  { char: "👿", name: "Angry Face with Horns", keywords: ["devil", "evil", "angry", "face"] },
  { char: "💀", name: "Skull", keywords: ["skull", "death", "dead", "danger"] },
  { char: "☠", name: "Skull and Crossbones", keywords: ["skull", "crossbones", "pirate", "poison"] },
  { char: "💩", name: "Pile of Poo", keywords: ["poop", "poo", "funny"] },
  { char: "🤡", name: "Clown Face", keywords: ["clown", "face", "funny"] },
  { char: "👹", name: "Ogre", keywords: ["ogre", "monster", "japanese"] },
  { char: "👺", name: "Goblin", keywords: ["goblin", "monster", "japanese"] },
  { char: "👻", name: "Ghost", keywords: ["ghost", "boo", "halloween", "spooky"] },
  { char: "👽", name: "Alien", keywords: ["alien", "extraterrestrial", "ufo"] },
  { char: "🤖", name: "Robot Face", keywords: ["robot", "android", "bot", "face"] },
  { char: "😺", name: "Grinning Cat Face", keywords: ["cat", "smile", "happy", "face"] },
  { char: "😸", name: "Grinning Cat Face with Smiling Eyes", keywords: ["cat", "smile", "face"] },
  { char: "😹", name: "Cat Face with Tears of Joy", keywords: ["cat", "laugh", "cry", "joy"] },
  { char: "😻", name: "Smiling Cat Face with Heart-Eyes", keywords: ["cat", "love", "heart", "face"] },
  { char: "😼", name: "Cat Face with Wry Smile", keywords: ["cat", "smirk", "face"] },
  { char: "😽", name: "Kissing Cat Face with Closed Eyes", keywords: ["cat", "kiss", "face"] },
  { char: "🙀", name: "Weary Cat Face", keywords: ["cat", "weary", "shocked", "face"] },
  { char: "😿", name: "Crying Cat Face", keywords: ["cat", "cry", "sad", "face"] },
  { char: "😾", name: "Pouting Cat Face", keywords: ["cat", "pout", "grumpy", "face"] },

  // ── Animals ────────────────────────────────────────────────────────────
  { char: "🐶", name: "Dog Face", keywords: ["dog", "puppy", "animal"] },
  { char: "🐱", name: "Cat Face", keywords: ["cat", "kitten", "animal"] },
  { char: "🐭", name: "Mouse Face", keywords: ["mouse", "animal"] },
  { char: "🐹", name: "Hamster Face", keywords: ["hamster", "animal"] },
  { char: "🐰", name: "Rabbit Face", keywords: ["rabbit", "bunny", "animal"] },
  { char: "🦊", name: "Fox Face", keywords: ["fox", "animal"] },
  { char: "🐻", name: "Bear Face", keywords: ["bear", "animal"] },
  { char: "🐼", name: "Panda Face", keywords: ["panda", "animal"] },
  { char: "🐨", name: "Koala", keywords: ["koala", "animal"] },
  { char: "🐯", name: "Tiger Face", keywords: ["tiger", "animal"] },
  { char: "🦁", name: "Lion Face", keywords: ["lion", "animal"] },
  { char: "🐮", name: "Cow Face", keywords: ["cow", "animal"] },
  { char: "🐷", name: "Pig Face", keywords: ["pig", "animal"] },
  { char: "🐸", name: "Frog Face", keywords: ["frog", "animal"] },
  { char: "🐵", name: "Monkey Face", keywords: ["monkey", "animal"] },
  { char: "🐔", name: "Chicken", keywords: ["chicken", "hen", "animal"] },
  { char: "🐧", name: "Penguin", keywords: ["penguin", "animal"] },
  { char: "🐦", name: "Bird", keywords: ["bird", "animal"] },
  { char: "🦆", name: "Duck", keywords: ["duck", "animal"] },
  { char: "🦅", name: "Eagle", keywords: ["eagle", "bird", "animal"] },
  { char: "🦉", name: "Owl", keywords: ["owl", "bird", "animal"] },
  { char: "🦋", name: "Butterfly", keywords: ["butterfly", "insect", "animal"] },
  { char: "🐛", name: "Bug", keywords: ["bug", "caterpillar", "insect"] },
  { char: "🐝", name: "Honeybee", keywords: ["bee", "honey", "insect"] },
  { char: "🐞", name: "Lady Beetle", keywords: ["ladybug", "ladybird", "insect"] },
  { char: "🦎", name: "Lizard", keywords: ["lizard", "reptile", "animal"] },
  { char: "🐍", name: "Snake", keywords: ["snake", "reptile", "animal"] },
  { char: "🐢", name: "Turtle", keywords: ["turtle", "reptile", "animal"] },
  { char: "🦈", name: "Shark", keywords: ["shark", "fish", "ocean", "animal"] },
  { char: "🐳", name: "Spouting Whale", keywords: ["whale", "ocean", "animal"] },
  { char: "🐬", name: "Dolphin", keywords: ["dolphin", "ocean", "animal"] },
  { char: "🦄", name: "Unicorn", keywords: ["unicorn", "magical", "animal"] },
  { char: "🐲", name: "Dragon Face", keywords: ["dragon", "mythical", "animal"] },

  // ── Plants & Nature ───────────────────────────────────────────────────
  { char: "🌸", name: "Cherry Blossom", keywords: ["cherry", "blossom", "flower", "japan"] },
  { char: "💐", name: "Bouquet", keywords: ["bouquet", "flowers", "gift"] },
  { char: "🌹", name: "Rose", keywords: ["rose", "flower", "red", "love"] },
  { char: "🥀", name: "Wilted Flower", keywords: ["flower", "wilted", "dead"] },
  { char: "🌷", name: "Tulip", keywords: ["tulip", "flower"] },
  { char: "🌻", name: "Sunflower", keywords: ["sunflower", "flower", "yellow"] },
  { char: "🌼", name: "Blossom", keywords: ["blossom", "flower", "yellow"] },
  { char: "🍀", name: "Four Leaf Clover", keywords: ["clover", "lucky", "four", "leaf"] },
  { char: "🌿", name: "Herb", keywords: ["herb", "leaf", "green"] },
  { char: "🍁", name: "Maple Leaf", keywords: ["maple", "leaf", "autumn", "canada"] },
  { char: "🍂", name: "Fallen Leaf", keywords: ["leaf", "fallen", "autumn"] },
  { char: "🍃", name: "Leaf Fluttering in Wind", keywords: ["leaf", "wind", "green"] },
  { char: "🌲", name: "Evergreen Tree", keywords: ["tree", "evergreen", "pine"] },
  { char: "🌳", name: "Deciduous Tree", keywords: ["tree", "deciduous", "nature"] },
  { char: "🌴", name: "Palm Tree", keywords: ["palm", "tree", "tropical"] },
  { char: "🌵", name: "Cactus", keywords: ["cactus", "desert", "plant"] },
  { char: "🌾", name: "Sheaf of Rice", keywords: ["rice", "grain", "farm"] },
  { char: "🍄", name: "Mushroom", keywords: ["mushroom", "fungus"] },
  { char: "🌱", name: "Seedling", keywords: ["seedling", "sprout", "grow"] },

  // ── Food & Drink ──────────────────────────────────────────────────────
  { char: "🍎", name: "Red Apple", keywords: ["apple", "red", "fruit"] },
  { char: "🍊", name: "Tangerine", keywords: ["orange", "tangerine", "fruit"] },
  { char: "🍋", name: "Lemon", keywords: ["lemon", "citrus", "fruit"] },
  { char: "🍇", name: "Grapes", keywords: ["grapes", "fruit"] },
  { char: "🍓", name: "Strawberry", keywords: ["strawberry", "fruit"] },
  { char: "🍒", name: "Cherries", keywords: ["cherry", "fruit"] },
  { char: "🍑", name: "Peach", keywords: ["peach", "fruit"] },
  { char: "🥭", name: "Mango", keywords: ["mango", "fruit"] },
  { char: "🍕", name: "Pizza", keywords: ["pizza", "food"] },
  { char: "🍔", name: "Hamburger", keywords: ["burger", "hamburger", "food"] },
  { char: "🍟", name: "French Fries", keywords: ["fries", "potato", "food"] },
  { char: "🌮", name: "Taco", keywords: ["taco", "mexican", "food"] },
  { char: "🍣", name: "Sushi", keywords: ["sushi", "japanese", "food"] },
  { char: "☕", name: "Hot Beverage", keywords: ["coffee", "tea", "hot", "drink"] },
  { char: "🍵", name: "Teacup Without Handle", keywords: ["tea", "green", "drink"] },
  { char: "🧋", name: "Bubble Tea", keywords: ["bubble", "tea", "boba", "drink"] },
  { char: "🍺", name: "Beer Mug", keywords: ["beer", "drink", "alcohol"] },
  { char: "🍷", name: "Wine Glass", keywords: ["wine", "drink", "alcohol"] },

  // ── Transportation ─────────────────────────────────────────────────────
  { char: "🚗", name: "Automobile", keywords: ["car", "auto", "vehicle"] },
  { char: "🚕", name: "Taxi", keywords: ["taxi", "cab", "vehicle"] },
  { char: "🚙", name: "Sport Utility Vehicle", keywords: ["suv", "car", "vehicle"] },
  { char: "🚌", name: "Bus", keywords: ["bus", "vehicle", "transport"] },
  { char: "🚎", name: "Trolleybus", keywords: ["trolley", "bus", "transport"] },
  { char: "🏎", name: "Racing Car", keywords: ["race", "car", "fast", "formula"] },
  { char: "🚓", name: "Police Car", keywords: ["police", "car", "cop"] },
  { char: "🚑", name: "Ambulance", keywords: ["ambulance", "emergency", "medical"] },
  { char: "🚒", name: "Fire Engine", keywords: ["fire", "truck", "emergency"] },
  { char: "✈", name: "Airplane", keywords: ["airplane", "plane", "fly", "travel"] },
  { char: "🚂", name: "Locomotive", keywords: ["train", "locomotive", "transport"] },
  { char: "🚢", name: "Ship", keywords: ["ship", "boat", "ocean", "travel"] },
  { char: "⚓", name: "Anchor", keywords: ["anchor", "ship", "nautical"] },
  { char: "🚲", name: "Bicycle", keywords: ["bike", "bicycle", "cycling"] },
  { char: "🛵", name: "Motor Scooter", keywords: ["scooter", "moped", "vehicle"] },
  { char: "🏍", name: "Motorcycle", keywords: ["motorcycle", "motorbike"] },
  { char: "🚁", name: "Helicopter", keywords: ["helicopter", "fly", "rotor"] },
  { char: "🛶", name: "Canoe", keywords: ["canoe", "boat", "paddle"] },
  { char: "⛵", name: "Sailboat", keywords: ["sail", "boat", "wind", "ocean"] },

  // ── Flags & Symbols ───────────────────────────────────────────────────
  { char: "🏁", name: "Chequered Flag", keywords: ["flag", "finish", "race", "checkered"] },
  { char: "🚩", name: "Triangular Flag", keywords: ["flag", "red", "warning"] },
  { char: "🎌", name: "Crossed Flags", keywords: ["flag", "japan", "crossed"] },
  { char: "🏴", name: "Black Flag", keywords: ["flag", "black", "pirate"] },
  { char: "🏳", name: "White Flag", keywords: ["flag", "white", "surrender"] },

  // ── Special Unicode Symbols ────────────────────────────────────────────
  { char: "⌘", name: "Place of Interest Sign", keywords: ["command", "mac", "apple", "key"] },
  { char: "⌥", name: "Option Key", keywords: ["option", "alt", "mac", "key"] },
  { char: "⇧", name: "Upwards White Arrow", keywords: ["shift", "key", "arrow"] },
  { char: "⌫", name: "Erase to the Left", keywords: ["backspace", "delete", "key"] },
  { char: "⌦", name: "Erase to the Right", keywords: ["delete", "forward", "key"] },
  { char: "⏎", name: "Return Symbol", keywords: ["return", "enter", "key"] },
  { char: "⇥", name: "Rightwards Arrow to Bar", keywords: ["tab", "key"] },
  { char: "⇤", name: "Leftwards Arrow to Bar", keywords: ["tab", "back", "key"] },
  { char: "⎋", name: "Broken Circle with Northwest Arrow", keywords: ["escape", "esc", "key"] },
  { char: "⏏", name: "Eject Symbol", keywords: ["eject", "media", "key"] },
  { char: "⌃", name: "Up Arrowhead", keywords: ["control", "ctrl", "mac", "key"] },
  { char: "␣", name: "Open Box", keywords: ["space", "key", "blank"] },
  { char: "⌤", name: "Up Arrowhead Between Two Horizontal Bars", keywords: ["enter", "key"] },
  { char: "✦", name: "Black Four Pointed Star", keywords: ["sparkle", "star", "four"] },
  { char: "✴", name: "Eight Pointed Black Star", keywords: ["star", "eight", "pointed"] },
  { char: "❈", name: "Heavy Sparkle", keywords: ["sparkle", "heavy"] },
  { char: "❉", name: "Balloon-Spoked Asterisk", keywords: ["asterisk", "balloon"] },
  { char: "❊", name: "Eight Teardrop-Spoked Propeller Asterisk", keywords: ["asterisk", "propeller"] },
  { char: "❋", name: "Heavy Eight Teardrop-Spoked Propeller Asterisk", keywords: ["asterisk", "heavy"] },
  { char: "✾", name: "Six Petalled Black and White Florette", keywords: ["flower", "petal", "florette"] },
  { char: "❁", name: "Eight Petalled Outlined Black Florette", keywords: ["flower", "petal", "outlined"] },
  { char: "❀", name: "White Florette", keywords: ["flower", "petal", "white"] },
  { char: "✿", name: "Black Florette", keywords: ["flower", "petal", "black"] },
  { char: "❃", name: "Heavy Teardrop-Spoked Pinwheel Asterisk", keywords: ["asterisk", "pinwheel"] },
  { char: "❂", name: "Circled Open Centre Eight Pointed Star", keywords: ["star", "circled"] },
  { char: "✼", name: "Open Centre Teardrop-Spoked Asterisk", keywords: ["asterisk", "open"] },
  { char: "✻", name: "Teardrop-Spoked Asterisk", keywords: ["asterisk", "teardrop"] },
  { char: "✺", name: "Twelve Pointed Black Star", keywords: ["star", "twelve"] },
  { char: "✹", name: "Twelve Pointed Pinwheel Star", keywords: ["star", "pinwheel"] },
  { char: "✸", name: "Heavy Eight Pointed Rectilinear Black Star", keywords: ["star", "eight", "heavy"] },
  { char: "✷", name: "Eight Pointed Rectilinear Black Star", keywords: ["star", "eight", "rectilinear"] },
  { char: "✶", name: "Six Pointed Black Star", keywords: ["star", "six", "david"] },
  { char: "✵", name: "Eight Pointed Pinwheel Star", keywords: ["star", "eight", "pinwheel"] },
  { char: "✳", name: "Eight Spoked Asterisk", keywords: ["asterisk", "eight", "spoked"] },

  // ── Zodiac & Astrology ─────────────────────────────────────────────────
  { char: "♈", name: "Aries", keywords: ["aries", "zodiac", "ram"] },
  { char: "♉", name: "Taurus", keywords: ["taurus", "zodiac", "bull"] },
  { char: "♊", name: "Gemini", keywords: ["gemini", "zodiac", "twins"] },
  { char: "♋", name: "Cancer", keywords: ["cancer", "zodiac", "crab"] },
  { char: "♌", name: "Leo", keywords: ["leo", "zodiac", "lion"] },
  { char: "♍", name: "Virgo", keywords: ["virgo", "zodiac"] },
  { char: "♎", name: "Libra", keywords: ["libra", "zodiac", "scales"] },
  { char: "♏", name: "Scorpius", keywords: ["scorpio", "scorpius", "zodiac"] },
  { char: "♐", name: "Sagittarius", keywords: ["sagittarius", "zodiac", "archer"] },
  { char: "♑", name: "Capricorn", keywords: ["capricorn", "zodiac", "goat"] },
  { char: "♒", name: "Aquarius", keywords: ["aquarius", "zodiac", "water"] },
  { char: "♓", name: "Pisces", keywords: ["pisces", "zodiac", "fish"] },
  { char: "⛎", name: "Ophiuchus", keywords: ["ophiuchus", "zodiac", "serpent"] },

  // ── Playing Cards & Games ─────────────────────────────────────────────
  { char: "♠", name: "Black Spade Suit", keywords: ["spade", "card", "suit"] },
  { char: "♣", name: "Black Club Suit", keywords: ["club", "card", "suit"] },
  { char: "♦", name: "Black Diamond Suit", keywords: ["diamond", "card", "suit"] },
  { char: "♥", name: "Black Heart Suit", keywords: ["heart", "card", "suit"] },
  { char: "🃏", name: "Joker", keywords: ["joker", "card", "wild"] },
  { char: "🎴", name: "Flower Playing Cards", keywords: ["card", "flower", "japanese"] },

  // ── Weather & Sky ──────────────────────────────────────────────────────
  { char: "🌤", name: "Sun Behind Small Cloud", keywords: ["sun", "cloud", "partly", "weather"] },
  { char: "🌥", name: "Sun Behind Large Cloud", keywords: ["sun", "cloud", "cloudy"] },
  { char: "🌦", name: "Sun Behind Rain Cloud", keywords: ["sun", "rain", "weather"] },
  { char: "🌧", name: "Cloud with Rain", keywords: ["rain", "cloud", "weather"] },
  { char: "🌨", name: "Cloud with Snow", keywords: ["snow", "cloud", "weather"] },
  { char: "🌩", name: "Cloud with Lightning", keywords: ["lightning", "storm", "weather"] },
  { char: "🌪", name: "Tornado", keywords: ["tornado", "twister", "storm"] },
  { char: "🌫", name: "Fog", keywords: ["fog", "mist", "weather"] },
  { char: "🌬", name: "Wind Face", keywords: ["wind", "blow", "weather"] },
  { char: "🌀", name: "Cyclone", keywords: ["cyclone", "spiral", "wind"] },
  { char: "🌊", name: "Water Wave", keywords: ["wave", "ocean", "water"] },
  { char: "💧", name: "Droplet", keywords: ["drop", "water", "rain"] },
  { char: "💦", name: "Splashing Sweat Droplets", keywords: ["water", "splash", "drops"] },
  { char: "🔆", name: "High Brightness Symbol", keywords: ["bright", "brightness", "sun"] },
  { char: "🔅", name: "Low Brightness Symbol", keywords: ["dim", "brightness"] },
  { char: "🌡", name: "Thermometer", keywords: ["thermometer", "temperature", "weather"] },
  { char: "🌂", name: "Closed Umbrella", keywords: ["umbrella", "rain", "weather"] },
  { char: "☂", name: "Umbrella", keywords: ["umbrella", "rain", "open"] },
  { char: "☃", name: "Snowman", keywords: ["snowman", "winter", "snow"] },
  { char: "⛄", name: "Snowman Without Snow", keywords: ["snowman", "winter"] },
  { char: "🌈", name: "Rainbow", keywords: ["rainbow", "color", "weather"] },

  // ── Numbers & Fractions ────────────────────────────────────────────────
  { char: "½", name: "Vulgar Fraction One Half", keywords: ["half", "fraction", "1/2"] },
  { char: "⅓", name: "Vulgar Fraction One Third", keywords: ["third", "fraction", "1/3"] },
  { char: "¼", name: "Vulgar Fraction One Quarter", keywords: ["quarter", "fraction", "1/4"] },
  { char: "¾", name: "Vulgar Fraction Three Quarters", keywords: ["three", "quarter", "fraction", "3/4"] },
  { char: "⅔", name: "Vulgar Fraction Two Thirds", keywords: ["two", "third", "fraction", "2/3"] },
  { char: "⅕", name: "Vulgar Fraction One Fifth", keywords: ["fifth", "fraction", "1/5"] },
  { char: "⅛", name: "Vulgar Fraction One Eighth", keywords: ["eighth", "fraction", "1/8"] },

  // ── Box Drawing ────────────────────────────────────────────────────────
  { char: "─", name: "Box Drawings Light Horizontal", keywords: ["box", "line", "horizontal"] },
  { char: "│", name: "Box Drawings Light Vertical", keywords: ["box", "line", "vertical"] },
  { char: "┌", name: "Box Drawings Light Down and Right", keywords: ["box", "corner", "top", "left"] },
  { char: "┐", name: "Box Drawings Light Down and Left", keywords: ["box", "corner", "top", "right"] },
  { char: "└", name: "Box Drawings Light Up and Right", keywords: ["box", "corner", "bottom", "left"] },
  { char: "┘", name: "Box Drawings Light Up and Left", keywords: ["box", "corner", "bottom", "right"] },
  { char: "├", name: "Box Drawings Light Vertical and Right", keywords: ["box", "tee", "left"] },
  { char: "┤", name: "Box Drawings Light Vertical and Left", keywords: ["box", "tee", "right"] },
  { char: "┬", name: "Box Drawings Light Down and Horizontal", keywords: ["box", "tee", "down"] },
  { char: "┴", name: "Box Drawings Light Up and Horizontal", keywords: ["box", "tee", "up"] },
  { char: "┼", name: "Box Drawings Light Vertical and Horizontal", keywords: ["box", "cross", "plus"] },
  { char: "═", name: "Box Drawings Double Horizontal", keywords: ["box", "double", "horizontal"] },
  { char: "║", name: "Box Drawings Double Vertical", keywords: ["box", "double", "vertical"] },
  { char: "╔", name: "Box Drawings Double Down and Right", keywords: ["box", "double", "corner", "top"] },
  { char: "╗", name: "Box Drawings Double Down and Left", keywords: ["box", "double", "corner"] },
  { char: "╚", name: "Box Drawings Double Up and Right", keywords: ["box", "double", "corner", "bottom"] },
  { char: "╝", name: "Box Drawings Double Up and Left", keywords: ["box", "double", "corner"] },
  { char: "╠", name: "Box Drawings Double Vertical and Right", keywords: ["box", "double", "tee"] },
  { char: "╣", name: "Box Drawings Double Vertical and Left", keywords: ["box", "double", "tee"] },
  { char: "╦", name: "Box Drawings Double Down and Horizontal", keywords: ["box", "double", "tee"] },
  { char: "╩", name: "Box Drawings Double Up and Horizontal", keywords: ["box", "double", "tee"] },
  { char: "╬", name: "Box Drawings Double Vertical and Horizontal", keywords: ["box", "double", "cross"] },

  // ── Supplemental ─────────────────────────────────────────────────────
  { char: "⁴", name: "Superscript Four", keywords: ["superscript", "four", "exponent"] },
  { char: "ℏ", name: "Planck Constant over Two Pi", keywords: ["planck", "physics", "hbar", "quantum"] },
  { char: "ℓ", name: "Script Small l", keywords: ["script", "l", "liter", "math"] },
  { char: "ℝ", name: "Double-Struck Capital R", keywords: ["real", "numbers", "math", "double"] },
  { char: "ℤ", name: "Double-Struck Capital Z", keywords: ["integer", "numbers", "math", "double"] },
  { char: "ℕ", name: "Double-Struck Capital N", keywords: ["natural", "numbers", "math", "double"] },
  { char: "ℚ", name: "Double-Struck Capital Q", keywords: ["rational", "numbers", "math", "double"] },
  { char: "ℂ", name: "Double-Struck Capital C", keywords: ["complex", "numbers", "math", "double"] },
  { char: "⊞", name: "Squared Plus", keywords: ["plus", "square", "box"] },
  { char: "⊟", name: "Squared Minus", keywords: ["minus", "square", "box"] },
  { char: "⊠", name: "Squared Times", keywords: ["times", "square", "box"] },
  { char: "⊡", name: "Squared Dot Operator", keywords: ["dot", "square", "box"] },
  { char: "◰", name: "White Square with Upper Left Quadrant", keywords: ["square", "quadrant"] },
  { char: "◱", name: "White Square with Lower Left Quadrant", keywords: ["square", "quadrant"] },
  { char: "◲", name: "White Square with Lower Right Quadrant", keywords: ["square", "quadrant"] },
  { char: "◳", name: "White Square with Upper Right Quadrant", keywords: ["square", "quadrant"] },
  { char: "◴", name: "White Circle with Upper Left Quadrant", keywords: ["circle", "quadrant"] },
  { char: "◵", name: "White Circle with Lower Left Quadrant", keywords: ["circle", "quadrant"] },
  { char: "◶", name: "White Circle with Lower Right Quadrant", keywords: ["circle", "quadrant"] },
  { char: "◷", name: "White Circle with Upper Right Quadrant", keywords: ["circle", "quadrant"] },
  { char: "⌀", name: "Diameter Sign", keywords: ["diameter", "circle", "technical"] },
  { char: "⌁", name: "Electric Arrow", keywords: ["electric", "arrow", "technical"] },
  { char: "⌂", name: "House", keywords: ["house", "home", "technical"] },
  { char: "⌛", name: "Hourglass", keywords: ["hourglass", "time", "wait"] },
  { char: "⏰", name: "Alarm Clock", keywords: ["alarm", "clock", "time"] },
  { char: "⚡", name: "High Voltage", keywords: ["lightning", "bolt", "electric"] },
  { char: "⚽", name: "Soccer Ball", keywords: ["soccer", "football", "sport"] },
  { char: "⚾", name: "Baseball", keywords: ["baseball", "sport", "ball"] },
  { char: "🏀", name: "Basketball", keywords: ["basketball", "sport", "ball"] },
  { char: "🏈", name: "American Football", keywords: ["football", "american", "sport"] },
  { char: "🎾", name: "Tennis", keywords: ["tennis", "sport", "ball"] },
  { char: "🏐", name: "Volleyball", keywords: ["volleyball", "sport", "ball"] },
  { char: "🏉", name: "Rugby Football", keywords: ["rugby", "sport", "ball"] },
  { char: "🥏", name: "Flying Disc", keywords: ["frisbee", "disc", "sport"] },
  { char: "⛳", name: "Flag in Hole", keywords: ["golf", "flag", "sport"] },
  { char: "🎱", name: "Pool 8 Ball", keywords: ["billiards", "pool", "8ball", "sport"] },
  { char: "🏓", name: "Ping Pong", keywords: ["pingpong", "table", "tennis", "sport"] },
  { char: "🥊", name: "Boxing Glove", keywords: ["boxing", "glove", "sport"] },
  { char: "🎿", name: "Skis", keywords: ["ski", "snow", "winter", "sport"] },
  { char: "🛷", name: "Sled", keywords: ["sled", "snow", "winter"] },
  { char: "🥋", name: "Martial Arts Uniform", keywords: ["karate", "judo", "martial", "sport"] },
];
